---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pihole
  name: pihole
spec:
  containers:
  - image: pihole/pihole
    imagePullPolicy: Always
    name: pihole
    resources: {}
    ports:
      - containerPort: 80
        name: http
      - containerPort: 53
        protocol: TCP
        name: dns-tcp
      - containerPort: 53
        protocol: UDP
        name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pihole
  name: pihole-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pihole
---
